#! /usr/bin/env bash

set -x
set -e
set -u
set -o pipefail

# preconditions and setup
test -d .git
test -d packnback.github.io

if test -d ./packnback.github.io/public
then
	rm -rf ./packnback.github.io/public
fi

cd ./packnback.github.io


mkdir -p static
cat ../ledger.txt > static/ledger.txt
dot -Tpng < ./content/blog/dedup_and_encryption_fig1.gv > static/dedup_and_encryption_fig1.png

hugo -t packnback

